In [31]:
import numpy as np
import math

In [32]:
# CREACIÓN DE ARRAYS
a = np.array([1,2,3])
print(a)
print(a.ndim)
print(a.shape)

[1 2 3]
1
(3,)


In [33]:
b = np.array([[1,2.3,True],[4,5,6]])
print(b)
print(b.ndim)
print(b.shape)

[[1.  2.3 1. ]
 [4.  5.  6. ]]
2
(2, 3)


In [34]:
b.dtype

dtype('float64')

In [35]:
d = np.zeros((2,3))
e = np.ones((2,3))
print(d)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [36]:
np.random.rand(2,3)

array([[0.56514253, 0.75527187, 0.98852103],
       [0.05166966, 0.78050527, 0.36185312]])

In [37]:
print(np.arange(10,50,2))
list(range(10,50,2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


[10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48]

In [38]:
np.arange(0,5,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [39]:
np.linspace(0,5,30)

array([0.        , 0.17241379, 0.34482759, 0.51724138, 0.68965517,
       0.86206897, 1.03448276, 1.20689655, 1.37931034, 1.55172414,
       1.72413793, 1.89655172, 2.06896552, 2.24137931, 2.4137931 ,
       2.5862069 , 2.75862069, 2.93103448, 3.10344828, 3.27586207,
       3.44827586, 3.62068966, 3.79310345, 3.96551724, 4.13793103,
       4.31034483, 4.48275862, 4.65517241, 4.82758621, 5.        ])

In [40]:
# OPERACIÓN DE ARRAYS
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

In [41]:
c = a-b
print(c)

[ 9 18 27 36]


In [42]:
d = a*b
print(d)
print(np.dot(a,b))
print(a@b)

[ 10  40  90 160]
300
300


In [43]:
# Usando listas
farenheit = [0,-10,-5,-15,0]
celsius = []
for temp in farenheit:
    celsius_temp = (temp-31)*(5/9)
    celsius.append(celsius_temp)
celsius

# Usando numpy
farenheit = np.array([0,-10,-5,-15,0])
celsius = (farenheit-31)*(5/9)
celsius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [44]:
# Arrays booleanos
celsius > -20

array([ True, False, False, False,  True])

In [45]:
celsius%2 == 0

array([False, False,  True, False, False])

In [46]:
numeros = np.array([2,5,6,7,8,4,4,6,7,8,6,4,3])
numeros%2 == 0

array([ True, False,  True, False,  True,  True,  True,  True, False,
        True,  True,  True, False])

In [47]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A)
print(B)
print(A*B)
print(A@B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [48]:
A = np.array([[1,1,5],[0,1,67]])
B = np.array([[2,0],[3,4],[6,4]])
print(A)
print(B)
print(A@B)
print(np.dot(A,B))
print(A.shape)
print(B.shape)

[[ 1  1  5]
 [ 0  1 67]]
[[2 0]
 [3 4]
 [6 4]]
[[ 35  24]
 [405 272]]
[[ 35  24]
 [405 272]]
(2, 3)
(3, 2)


In [49]:
B = np.array([[2,True],[3.0,4],[6,4]])
B.dtype

dtype('float64')

In [50]:
#B = np.array([[2,0,5],[3,4,6],[6,4,7]])
#np.linalg.eig(B)

In [51]:
a = np.array([7,-5,0.67,8])
a.sum()
a.max()
a.min()
a.mean()

2.6675

In [52]:
b = np.arange(1,16,1).reshape(5,3).mean()
b

8.0

In [53]:
# INDEXACIÓN, SLICING E ITERACIÓN
# Indexación por enteros
a = np.array([1,3,5,7])
a[1]

3

In [54]:
a = np.array([[1,2,4],[6,4,3],[1,3,5]])
print(a)
print(a[0,-1])
np.array([a[0,0],a[1,1],a[2,2]])

[[1 2 4]
 [6 4 3]
 [1 3 5]]
4


array([1, 4, 5])

In [55]:
# Indexación booleana
farenheit = np.array([0,-10,-5,-15,0])
celsius = (farenheit-31)*(5/9)

condicion = celsius > -20 
celsius[condicion]

array([-17.22222222, -17.22222222])

In [56]:
celsius1 = np.zeros(len(celsius))
for i,val in enumerate(celsius):
    if val >-20:
        celsius1[i] = val
celsius1

array([-17.22222222,   0.        ,   0.        ,   0.        ,
       -17.22222222])

In [57]:
# SLICING
a = np.array([0,1,2,3,4,5,6])
print(a[0:3])

[0 1 2]


In [58]:
a = np.array([[0,1,3,4,5.0],[4,5,6,6,5],[4,5,7,8,9],[-5,-6,-7,-1,-2]])
print(a)
a[1:3,1:4]

[[ 0.  1.  3.  4.  5.]
 [ 4.  5.  6.  6.  5.]
 [ 4.  5.  7.  8.  9.]
 [-5. -6. -7. -1. -2.]]


array([[5., 6., 6.],
       [5., 7., 8.]])

In [59]:
a[1,3] = np.nan
a

array([[ 0.,  1.,  3.,  4.,  5.],
       [ 4.,  5.,  6., nan,  5.],
       [ 4.,  5.,  7.,  8.,  9.],
       [-5., -6., -7., -1., -2.]])

In [60]:
import numpy as np
wines = np.genfromtxt("datasets/winequality-red.csv",delimiter=';',skip_header=1)
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [61]:
wines[:,0]
wines[:,0:1]

array([[7.4],
       [7.8],
       [7.8],
       ...,
       [6.3],
       [5.9],
       [6. ]])

In [62]:
wines[:,[0,1,2]]
wines[:,0:3]

array([[7.4  , 0.7  , 0.   ],
       [7.8  , 0.88 , 0.   ],
       [7.8  , 0.76 , 0.04 ],
       ...,
       [6.3  , 0.51 , 0.13 ],
       [5.9  , 0.645, 0.12 ],
       [6.   , 0.31 , 0.47 ]])

In [63]:
wines[:,[0,2,4]]

array([[7.4  , 0.   , 0.076],
       [7.8  , 0.   , 0.098],
       [7.8  , 0.04 , 0.092],
       ...,
       [6.3  , 0.13 , 0.076],
       [5.9  , 0.12 , 0.075],
       [6.   , 0.47 , 0.067]])

In [64]:
wines[:,-1].mean()

5.6360225140712945

In [65]:
graduate_admission = np.genfromtxt("datasets/Admission_Predict.csv",dtype=None,delimiter=',',skip_header=1,names=('Serial No','GRE Score','TOEFL Score','University Rating','SOP','LOR','CGPA','Research','Chance_of_Admit'))


In [66]:
#graduate_admission

In [67]:
graduate_admission['CGPA'][0:5]

array([9.65, 8.87, 8.  , 8.67, 8.21])

In [68]:
graduate_admission['CGPA'] = graduate_admission['CGPA']/graduate_admission['CGPA'].max()

In [69]:
len(graduate_admission)

400

In [70]:
condition = graduate_admission['Research']==1
len(graduate_admission[condition])/len(graduate_admission)

0.5475

In [71]:
condicion1 = graduate_admission['Chance_of_Admit']>0.8
print(graduate_admission[condicion1]['GRE_Score'].mean())
condicion2 = graduate_admission['Chance_of_Admit']<0.4
print(graduate_admission[condicion2]['GRE_Score'].mean())

328.7350427350427
302.2857142857143
